Atom = GaN

DIM = 4 4 3

FORCE_CONSTANTS = read 

BAND = 0 0 0  0.3333 0.3333 0  0.5 0 0  0 0 0  0 0 0.5  0.3333 0.3333 0.5  0.5 0 0.5  0 0 0.5  
#      Gamma  K                M        Gamma  A        H                  L          A

EIGENVECTORS = .TRUE.

BAND_POINTS = 1001

SYMMETRY = .TRUE.

FC_SYMMETRY = .TRUE.
